# Generated by Django 5.1.6 on 2025-02-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_de_usuario", models.CharField(max_length=50, unique=True)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contraseña", models.CharField(max_length=128)),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("puntuacion_python", models.IntegerField(default=0)),
                ("puntuacion_c_mas_mas", models.IntegerField(default=0)),
                ("puntuacion_golang", models.IntegerField(default=0)),
                ("preguntas_respondidas", models.IntegerField(default=0)),
                ("url", models.URLField(null=True)),
                ("sobre_mi", models.TextField(null=True)),
            ],
        ),
    ]
